//export  {default as Auth } from './Auth'
export  {default as Login } from './Login'
export  {default as Register } from './Register'
export  {default as AdminLogin } from './AdminLogin'
export  {default as RegistrationPayment } from './RegistrationPayment'